# Generated by Django 6.1 on 2026-09-06 00:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterPF',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LanguagePF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Online class',
                'verbose_name_plural': 'Online classes',
            },
        ),
        migrations.CreateModel(
            name='ChapterPF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('link', models.ManyToManyField(blank=True, to='parsons_faded.chapterlink')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='DropOutModelPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.CharField(max_length=200)),
                ('completed_chapter', models.ManyToManyField(to='parsons_faded.chapterpf')),
            ],
            options={
                'verbose_name': 'Drop out model',
                'verbose_name_plural': 'Drop out models',
            },
        ),
        migrations.AddField(
            model_name='chapterpf',
            name='drop_out_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsons_faded.dropoutmodelpf'),
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsons_faded.chapterpf')),
            ],
            options={
                'verbose_name': 'Exercise Set',
                'verbose_name_plural': 'Exercises Sets',
            },
        ),
        migrations.CreateModel(
            name='HistoricalChapterPF',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('label', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('drop_out_model', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parsons_faded.dropoutmodelpf')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Chapter',
                'verbose_name_plural': 'historical Chapters',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOnlineClass',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Online class',
                'verbose_name_plural': 'historical Online classes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProblemPF',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('C', 'Code'), ('M', 'Multiple Choice'), ('T', 'Text'), ('P', 'Parsons Problem'), ('F', 'Parsons Faded Problem')], default='C', max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('options', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('retrieved_date', models.DateTimeField(blank=True, editable=False)),
                ('crawler', models.CharField(blank=True, max_length=200)),
                ('hint', models.TextField(blank=True)),
                ('test_case_generator', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Problem',
                'verbose_name_plural': 'historical Problems',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProblemPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('C', 'Code'), ('M', 'Multiple Choice'), ('T', 'Text'), ('P', 'Parsons Problem'), ('F', 'Parsons Faded Problem')], default='C', max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('options', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('retrieved_date', models.DateTimeField(auto_now_add=True)),
                ('crawler', models.CharField(blank=True, max_length=200)),
                ('hint', models.TextField(blank=True)),
                ('test_case_generator', models.TextField(blank=True, null=True)),
                ('chapter', models.ManyToManyField(through='parsons_faded.ExerciseSet', to='parsons_faded.chapterpf')),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSolutionPF',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('content', models.TextField()),
                ('header', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('retrieved_date', models.DateTimeField(blank=True, editable=False)),
                ('ignore', models.BooleanField(default=False)),
                ('tip', models.TextField(blank=True, default='#Start your python function here')),
                ('return_type', models.CharField(blank=True, choices=[('int', 'int'), ('float', 'float'), ('double', 'double'), ('char', 'char'), ('long', 'long'), ('long long', 'long long'), ('short', 'short'), ('unsigned int', 'unsigned int'), ('unsigned long', 'unsigned long'), ('const char*', 'const char*')], max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cluster', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parsons_faded.clusterpf')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parsons_faded.problempf')),
            ],
            options={
                'verbose_name': 'historical Solution',
                'verbose_name_plural': 'historical Solutions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExerciseSet',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('chapter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parsons_faded.chapterpf')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parsons_faded.problempf')),
            ],
            options={
                'verbose_name': 'historical Exercise Set',
                'verbose_name_plural': 'historical Exercises Sets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsons_faded.problempf'),
        ),
        migrations.CreateModel(
            name='SolutionPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('header', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('retrieved_date', models.DateTimeField(auto_now_add=True)),
                ('ignore', models.BooleanField(default=False)),
                ('tip', models.TextField(blank=True, default='#Start your python function here')),
                ('return_type', models.CharField(blank=True, choices=[('int', 'int'), ('float', 'float'), ('double', 'double'), ('char', 'char'), ('long', 'long'), ('long long', 'long long'), ('short', 'short'), ('unsigned int', 'unsigned int'), ('unsigned long', 'unsigned long'), ('const char*', 'const char*')], max_length=50, null=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsons_faded.clusterpf')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parsons_faded.problempf')),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
            },
        ),
    ]
