# Generated by Django 6.0.5 on 2026-06-06 19:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('link', models.ManyToManyField(blank=True, to='parsons.chapterlink')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='DropOutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.CharField(max_length=200)),
                ('completed_chapter', models.ManyToManyField(to='parsons.chapter')),
            ],
            options={
                'verbose_name': 'Drop out model',
                'verbose_name_plural': 'Drop out models',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='drop_out_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsons.dropoutmodel'),
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsons.chapter')),
            ],
            options={
                'verbose_name': 'Exercise Set',
                'verbose_name_plural': 'Exercises Sets',
            },
        ),
        migrations.CreateModel(
            name='HistoricalChapter',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('label', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('drop_out_model', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parsons.dropoutmodel')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Chapter',
                'verbose_name_plural': 'historical Chapters',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProblem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('C', 'Code'), ('M', 'Multiple Choice'), ('T', 'Text'), ('P', 'Parsons Problem')], default='C', max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('options', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('retrieved_date', models.DateTimeField(blank=True, editable=False)),
                ('crawler', models.CharField(blank=True, max_length=200)),
                ('hint', models.TextField(blank=True)),
                ('test_case_generator', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Problem',
                'verbose_name_plural': 'historical Problems',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('C', 'Code'), ('M', 'Multiple Choice'), ('T', 'Text'), ('P', 'Parsons Problem')], default='C', max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('options', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, max_length=200)),
                ('link', models.URLField(blank=True)),
                ('retrieved_date', models.DateTimeField(auto_now_add=True)),
                ('crawler', models.CharField(blank=True, max_length=200)),
                ('hint', models.TextField(blank=True)),
                ('test_case_generator', models.TextField(blank=True, null=True)),
                ('chapter', models.ManyToManyField(through='parsons.ExerciseSet', to='parsons.chapter')),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
            },
        ),
        migrations.CreateModel(
            name='HistoricalExerciseSet',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('chapter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parsons.chapter')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parsons.problem')),
            ],
            options={
                'verbose_name': 'historical Exercise Set',
                'verbose_name_plural': 'historical Exercises Sets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsons.problem'),
        ),
    ]
