# Generated by Django 5.2.15 on 2026-06-27 15:29

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AlterField(
            model_name='chapterlink',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dropoutmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalexerciseset',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalproblem',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='HistoricalSolution',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('content', models.TextField()),
                ('header', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('retrieved_date', models.DateTimeField(blank=True, editable=False)),
                ('ignore', models.BooleanField(default=False)),
                ('tip', models.TextField(blank=True, default='#Start your python function here')),
                ('return_type', models.CharField(blank=True, choices=[('int', 'int'), ('float', 'float'), ('double', 'double'), ('char', 'char'), ('long', 'long'), ('long long', 'long long'), ('short', 'short'), ('unsigned int', 'unsigned int'), ('unsigned long', 'unsigned long'), ('const char*', 'const char*')], max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cluster', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parsons.cluster')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parsons.problem')),
                ('language', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parsons.language')),
            ],
            options={
                'verbose_name': 'historical Solution',
                'verbose_name_plural': 'historical Solutions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('header', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('retrieved_date', models.DateTimeField(auto_now_add=True)),
                ('ignore', models.BooleanField(default=False)),
                ('tip', models.TextField(blank=True, default='#Start your python function here')),
                ('return_type', models.CharField(blank=True, choices=[('int', 'int'), ('float', 'float'), ('double', 'double'), ('char', 'char'), ('long', 'long'), ('long long', 'long long'), ('short', 'short'), ('unsigned int', 'unsigned int'), ('unsigned long', 'unsigned long'), ('const char*', 'const char*')], max_length=50, null=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsons.cluster')),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='parsons.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parsons.problem')),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
            },
        ),
    ]
