# Generated by Django 5.2.15 on 2026-06-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsons', '0002_cluster_language_alter_chapterlink_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsolution',
            name='language',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='language',
        ),
    ]
