# Generated by Django 6.0.7 on 2026-07-30 16:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('parsons', '0003_remove_historicalsolution_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogView',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('final_outcome', models.CharField(max_length=2)),
                ('timestamp', models.DateTimeField()),
                ('seconds_in_code', models.IntegerField()),
                ('seconds_in_page', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Online class',
                'verbose_name_plural': 'Online classes',
            },
        ),
        migrations.AlterField(
            model_name='chapterlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dropoutmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalexerciseset',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalproblem',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalsolution',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='HistoricalOnlineClass',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Online class',
                'verbose_name_plural': 'historical Online classes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('F', 'Failed'), ('P', 'Passed'), ('S', 'Skipped')], max_length=2)),
                ('console', models.TextField(blank=True)),
                ('seconds_in_code', models.IntegerField()),
                ('seconds_in_page', models.IntegerField()),
                ('seconds_to_begin', models.IntegerField()),
                ('solution_lines', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('error_type', models.CharField(choices=[('C', 'Conceptual'), ('S', 'Syntax'), ('D', 'Distraction'), ('I', 'Interpretation')], default='D', max_length=2)),
                ('test_case_hits', models.IntegerField(blank=True, null=True)),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='parsons.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parsons.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parsons.onlineclass')),
            ],
            options={
                'verbose_name': 'User log',
                'verbose_name_plural': 'User logs',
            },
        ),
        migrations.CreateModel(
            name='UserLogError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=255)),
                ('userlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error', to='parsons.userlog')),
            ],
        ),
    ]
